### ISSUE TITLE
Error: no template named 'make_unique' in namespace 'std' while Building vasp

### ISSUE THREAD

**Issue by shahriar0651** [quic/vasp#2]
## Summary

While building vasp (See step 2 in Build: `./configure && make [-j6]`), there comes an error **vasp/driver/CarApp.cc:258:19: error: no template named 'make_unique' in namespace 'std'; did you mean 'veins::make_unique'?**

After searching for the error, it appears that make_unique is a C++14 feature and thus might not be available on my compiler with the following `c++ --version`.
```
c++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
```

## To Reproduce (for bugs)

1. Follow the installation guidelines until the section **Build**
2. Try building using `./configure && make [-j6]` 
3. See error while dealing with vasp

## Expected behavior

The building process should go smoothly as did for veins without an error (missing nameplate)

## Screenshots

![issu_With_make_unique](https://user-images.githubusercontent.com/43500534/197840352-a7eb1e68-1ca4-4702-a827-1366cd99d7d0.jpg)

## System Information (please complete the following information):

- OS: Ubuntu 20.04 
- Default c++ version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

## Additional context

Here are the PATH variables while I was building:
```
bash: /home/hasan/Desktop/InstalledApps/v2x-sim/vasp/bin:
/home/hasan/Desktop/InstalledApps/v2x-sim/veins/bin:
/home/hasan/Desktop/InstalledApps/v2x-sim/omnetpp/bin:
/home/hasan/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:
/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: No such file or directory
```

**Comment by raash1d** [comment]
@shahriar0651 Please modify your "configure.user" file for OMNET++
Please modify the line with `CXXFLAGS` (probably line 36) to `CXXFLAGS=-std=c++14`
Clean and recompile OMNET++, then try compiling VASP again.

**Comment by shahriar0651** [comment]
Thanks. After updating CXXFLAGS I see the following error: 

`clang: error: clang frontend command failed due to signal (use -v to see invocation)`

![next_error](https://user-images.githubusercontent.com/43500534/198146571-56875d3f-7bce-4cbf-a310-bb186db0716f.jpg)

Here are the versions of my compilers:

```
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
c++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
clang version 10.0.0-4ubuntu1 
```

Do I need to update anything to make them compatible?

**Comment by raash1d** [comment]
@shahriar0651 I tried to rebuild everything in an Ubuntu 20.04 instance.
I did encounter your earlier error with `make_unique`. However, after changing `CXXFLAGS` as suggested:
<img width="660" alt="image" src="https://user-images.githubusercontent.com/15528027/198348096-a0fb2444-d56e-426f-93a8-ee1dfaa77065.png">

... everything built right on the OMNET++ front
<img width="660" alt="image" src="https://user-images.githubusercontent.com/15528027/198347630-67a82e29-fcbf-4f78-b99b-63e70b2c3167.png">

... and on the VEINS-VASP front
<img width="610" alt="image" src="https://user-images.githubusercontent.com/15528027/198348353-ee739eff-7bb8-4fac-bcd4-5a6d27eb309c.png">

I have the same compiler versions as you:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/15528027/198349474-eb80d300-9bb0-4553-99a3-811a52c2bdd5.png">


Are you sure you used `make clean` or `make cleanall` in both OMNET++ and VEINS directories before recompiling?
Have you configured your paths correctly in your ".bashrc" file?

**Comment by shahriar0651** [comment]
Hi @raash1d, Thanks for your response. Rebuilding OMNet++ along with updating CXXFLAGS helped! Now there is no issue with the building. However, I am facing the following issue while running the simulation with `./run [-u Cmdenv]`

![third_error](https://user-images.githubusercontent.com/43500534/198351021-eee7b963-dbfe-4260-93af-815e6a8f9d9d.jpg)

Any suggestion would be highly appreciated. Thanks!

**Comment by raash1d** [comment]
This is common convention of usage instructions, anything inside a `[]` is optional.

If you want to use those options, you need to use them without the `[]`. e.g., `./run -u Cmdenv`.

P.S.: Thanks for raising this issue, I have updated the instructions regarding CXXFLAGS in the README.

**Comment by shahriar0651** [comment]
Got it. Now the simulation is working perfectly and generating the trace file. Thanks for your help!
